name: integre_plus_action_renault
description: TalentForge

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version:A.B.C+X --> A.B.C represents the versionName such as 1.0.0 - X (the number after the +) represents the versionCode such as 1, 2, 3, etc.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  get: ^5.0.0-release-candidate-6
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  pluto_grid: ^8.0.0
  flutter_bootstrap: any
  email_validator: ^3.0.0
  dropdown_button2: ^2.3.9
  pdf:
  printing: ^5.13.0
  extended_masked_text: ^3.0.1
  recase: ^4.1.0
  buttons_tabbar: ^1.3.12
  
  flex_color_scheme: ^7.3.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.50
  flutter_staggered_grid_view: ^0.7.0
  speedometer_chart: ^1.0.8
  font_awesome_flutter: ^10.7.0
  graphview: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.8
  drift_dev:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/
     - assets/fonts/report/

msix_config:
  display_name: TalentForge
  publisher_display_name: TalentForge
  identity_name: TalentForge.UNICESUMAR
  msix_version: 1.0.10.0
  publisher: CN=0A6E4754-6ACC-44ED-81F6-94B57BF2E8BC
  logo_path: C:\talentforge\reobote_pdv\assets\images\slogan.png
  capabilities: internetClient,systemManagement,pointOfService,bluetooth
  store: true     

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/slogan.png"
flutter_icons:
  image_path: "assets/images/slogan.png"
  android: true
  ios: true
  min_sdk_android: 24
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/slogan.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/slogan.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/slogan.png"