import 'package:pluto_grid/pluto_grid.dart';
import 'package:integre_plus_action_renault/app/infra/util.dart';

List<PlutoColumn> colaboradoresGridColumns({bool isForLookup = false}) {
  return <PlutoColumn>[
    PlutoColumn(
        title: "Colaboradorid",
        field: "colaboradorid",
        type: PlutoColumnType.number(
          format: '##########',
        ),
        enableFilterMenuItem: true,
        enableSetColumnsMenuItem: false,
        enableHideColumnMenuItem: false,
        titleTextAlign: PlutoColumnTextAlign.center,
        textAlign: PlutoColumnTextAlign.center,
        width: 100,
        hide: true),
    PlutoColumn(
      title: "Nome",
      field: "nome",
      type: PlutoColumnType.text(),
      formatter: Util.stringFormat,
      enableFilterMenuItem: true,
      enableSetColumnsMenuItem: false,
      enableHideColumnMenuItem: false,
      titleTextAlign: PlutoColumnTextAlign.center,
      textAlign: PlutoColumnTextAlign.left,
      width: 400,
    ),
    PlutoColumn(
      title: "Cargo atual",
      field: "cargoatual",
      type: PlutoColumnType.text(),
      formatter: Util.stringFormat,
      enableFilterMenuItem: true,
      enableSetColumnsMenuItem: false,
      enableHideColumnMenuItem: false,
      titleTextAlign: PlutoColumnTextAlign.center,
      textAlign: PlutoColumnTextAlign.left,
      width: 400,
    ),
    PlutoColumn(
      title: "Data admissão",
      field: "dataadmissao",
      type: PlutoColumnType.date(format: "dd/MM/yyyy"),
      enableFilterMenuItem: true,
      enableSetColumnsMenuItem: false,
      enableHideColumnMenuItem: false,
      titleTextAlign: PlutoColumnTextAlign.center,
      textAlign: PlutoColumnTextAlign.center,
      width: 200,
    ),
    PlutoColumn(
      title: "Experiência atual",
      field: "experienciaatual",
      type: PlutoColumnType.number(
        format: '##########',
      ),
      enableFilterMenuItem: true,
      enableSetColumnsMenuItem: false,
      enableHideColumnMenuItem: false,
      titleTextAlign: PlutoColumnTextAlign.center,
      textAlign: PlutoColumnTextAlign.center,
      width: 180,
    ),
    PlutoColumn(
      title: "Telefone",
      field: "telefone",
      type: PlutoColumnType.text(),
      formatter: Util.stringFormat,
      enableFilterMenuItem: true,
      enableSetColumnsMenuItem: false,
      enableHideColumnMenuItem: false,
      titleTextAlign: PlutoColumnTextAlign.center,
      textAlign: PlutoColumnTextAlign.left,
      width: 200,
    ),
    PlutoColumn(
      title: "Status",
      field: "status",
      type: PlutoColumnType.text(),
      formatter: Util.stringFormat,
      enableFilterMenuItem: true,
      enableSetColumnsMenuItem: false,
      enableHideColumnMenuItem: false,
      titleTextAlign: PlutoColumnTextAlign.center,
      textAlign: PlutoColumnTextAlign.left,
      width: 240,
    ),
  ];
}
